<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <!-- Kopiuj wszystkie pliki audio do folderu Resources w output -->
    <None Update="Resources\Audio\**\*" CopyToOutputDirectory="PreserveNewest" />
    <!-- Kopiuj wszystkie obrazy do folderu Resources w output -->
    <None Update="Resources\Images\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
